repos:
  - repo: local
    hooks:
      - id: clang-format
        name: Clang Format
        entry: bash clang_format_check.sh
        language: system
        types: [file]
        files: ".*\\.(c|h)$"
        stages: [pre-commit]

      - id: clang-tidy
        name: Clang Tidy
        entry: clang-tidy --fix --quiet
        language: system
        types: [file]
        files: ".*\\.(c|h)$"
        stages: [pre-commit]

      - id: cppcheck
        name: Cppcheck
        entry: cppcheck --enable=all --quiet
        language: system
        types: [file]
        files: ".*\\.(c|h)$"
        stages: [pre-commit]

      - id: c-naming-conventions
        name: Check C Naming Conventions
        entry: python3 c_coding_standards.py
        language: system
        types: [file]
        files: ".*\\.(c|h)$"
        stages: [pre-commit]
