repos:
  - repo: local
    hooks:
      - id: clang-format
        name: Clang Format
        entry: clang-format -i
        language: system
        types: [c]
        files: \.(c|h)$

      - id: clang-tidy
        name: Clang Tidy
        entry: clang-tidy --fix --quiet
        language: system
        types: [c]
        files: \.(c|h)$

      - id: cppcheck
        name: Cppcheck
        entry: cppcheck --enable=all --quiet
        language: system
        types: [c]
        files: \.(c|h)$

      - id: c-naming-conventions
        name: Check C Naming Conventions
        entry: python3 c_coding_standards.py
        language: system
        types: [c]
        files: \.(c|h)$

      - id: shellcheck
        name: ShellCheck
        entry: shellcheck
        language: system
        types: [shell]
        files: \.sh$

      - id: cmake-format
        name: CMake Format
        entry: cmake-format -i
        language: system
        types: [text]
        files: ^CMakeLists\.txt$|\.cmake$

      - id: hadolint
        name: Hadolint
        entry: hadolint
        language: system
        types: [dockerfile]
        files: Dockerfile

